-- ========================================================
-- WAMINNA HOTEL DATABASE SCHEMA
-- Target Database: Supabase PostgreSQL (waminna-staging)
-- ========================================================

-- 1. ENUMS & CUSTOM TYPES
CREATE TYPE public.room_type AS ENUM ('standard', 'deluxe', 'suite');
CREATE TYPE public.bed_type AS ENUM ('king', 'queen', 'twin');
CREATE TYPE public.room_status AS ENUM ('available', 'maintenance', 'occupied');
CREATE TYPE public.booking_status AS ENUM ('confirmed', 'pending', 'cancelled', 'completed');
CREATE TYPE public.payment_status AS ENUM ('paid', 'pending', 'refunded');
CREATE TYPE public.user_role AS ENUM ('guest', 'user', 'staff', 'owner');
CREATE TYPE public.addon_category AS ENUM ('dining', 'transport', 'wellness', 'convenience');

-- 2. PROFILES TABLE (Extends auth.users)
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    phone TEXT,
    role public.user_role NOT NULL DEFAULT 'user',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. ROOMS TABLE
CREATE TABLE public.rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    room_number TEXT NOT NULL UNIQUE,
    type public.room_type NOT NULL,
    capacity INT NOT NULL DEFAULT 2,
    bed_type public.bed_type NOT NULL,
    price_per_night NUMERIC(10, 2) NOT NULL,
    description TEXT NOT NULL,
    amenities TEXT[] DEFAULT '{}',
    photos TEXT[] DEFAULT '{}',
    status public.room_status NOT NULL DEFAULT 'available',
    size TEXT,
    view TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. ADDONS TABLE
CREATE TABLE public.addons (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    per_night BOOLEAN DEFAULT FALSE,
    category public.addon_category NOT NULL,
    icon TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. BOOKINGS TABLE
CREATE TABLE public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_reference TEXT UNIQUE NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    room_id BIGINT NOT NULL REFERENCES public.rooms(id) ON DELETE CASCADE,
    guest_first_name TEXT NOT NULL,
    guest_last_name TEXT NOT NULL,
    guest_email TEXT NOT NULL,
    guest_phone TEXT,
    special_requests TEXT,
    selected_addon_ids TEXT[] DEFAULT '{}',
    addon_total NUMERIC(10, 2) DEFAULT 0,
    check_in DATE NOT NULL,
    check_out DATE NOT NULL,
    guests_count INT NOT NULL DEFAULT 1,
    nights INT NOT NULL,
    subtotal NUMERIC(10, 2) NOT NULL,
    tax_amount NUMERIC(10, 2) NOT NULL,
    total_amount NUMERIC(10, 2) NOT NULL,
    status public.booking_status NOT NULL DEFAULT 'confirmed',
    payment_status public.payment_status NOT NULL DEFAULT 'paid',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. BLOCKED DATES TABLE
CREATE TABLE public.blocked_dates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES public.rooms(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    reason TEXT NOT NULL CHECK (reason IN ('booking', 'maintenance')),
    booking_id BIGINT REFERENCES public.bookings(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_room_date UNIQUE (room_id, date)
);

-- 7. REVIEWS TABLE
CREATE TABLE public.reviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    room_id BIGINT NOT NULL REFERENCES public.rooms(id) ON DELETE CASCADE,
    user_name TEXT NOT NULL,
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    comment TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ========================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ========================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.addons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blocked_dates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Helper: check if the calling user has staff or owner role
CREATE OR REPLACE FUNCTION public.is_staff_or_owner()
RETURNS BOOLEAN AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid()
      AND role IN ('staff', 'owner')
  );
$$ LANGUAGE sql SECURITY DEFINER;

-- Helper: check if the calling user is an owner
CREATE OR REPLACE FUNCTION public.is_owner()
RETURNS BOOLEAN AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid()
      AND role = 'owner'
  );
$$ LANGUAGE sql SECURITY DEFINER;

-- ---- Rooms: Public read, staff/owner write ----
CREATE POLICY "Public Read Rooms" ON public.rooms FOR SELECT USING (true);
CREATE POLICY "Staff Insert Rooms" ON public.rooms FOR INSERT
  WITH CHECK (public.is_staff_or_owner());
CREATE POLICY "Staff Update Rooms" ON public.rooms FOR UPDATE
  USING (public.is_staff_or_owner());
CREATE POLICY "Staff Delete Rooms" ON public.rooms FOR DELETE
  USING (public.is_staff_or_owner());

-- ---- Addons: Public read, owner write ----
CREATE POLICY "Public Read Addons" ON public.addons FOR SELECT USING (true);
CREATE POLICY "Owner Manage Addons" ON public.addons FOR ALL
  USING (public.is_owner()) WITH CHECK (public.is_owner());

-- ---- Reviews: Public read, authenticated insert ----
CREATE POLICY "Public Read Reviews" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "Auth Insert Reviews" ON public.reviews FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Staff Delete Reviews" ON public.reviews FOR DELETE
  USING (public.is_staff_or_owner());

-- ---- Blocked Dates: Public read, staff write ----
CREATE POLICY "Public Read Blocked Dates" ON public.blocked_dates FOR SELECT USING (true);
CREATE POLICY "Staff Manage Blocked Dates" ON public.blocked_dates FOR ALL
  USING (public.is_staff_or_owner()) WITH CHECK (public.is_staff_or_owner());

-- ---- Bookings: Anyone can book; users can see their own; staff see all ----
CREATE POLICY "Public Insert Bookings" ON public.bookings FOR INSERT WITH CHECK (true);
CREATE POLICY "Read Own Bookings" ON public.bookings FOR SELECT
  USING (
    auth.uid() IS NULL -- allow lookup by reference for unauthenticated guests
    OR auth.uid() = user_id
    OR public.is_staff_or_owner()
  );
CREATE POLICY "Staff Update Bookings" ON public.bookings FOR UPDATE
  USING (public.is_staff_or_owner());

-- ---- Profiles: Users see own profile; staff see all ----
CREATE POLICY "Read Own Profile" ON public.profiles FOR SELECT
  USING (auth.uid() = id OR public.is_staff_or_owner());
CREATE POLICY "User Insert Own Profile" ON public.profiles FOR INSERT
  WITH CHECK (auth.uid() = id);
CREATE POLICY "User Update Own Profile" ON public.profiles FOR UPDATE
  USING (auth.uid() = id);
CREATE POLICY "Owner Update Any Profile" ON public.profiles FOR UPDATE
  USING (public.is_owner());

-- ========================================================
-- AUTO-PROFILE TRIGGER
-- Creates a profiles row automatically when a user signs up via Supabase Auth.
-- ========================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, first_name, last_name, role)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'first_name', ''),
    COALESCE(NEW.raw_user_meta_data->>'last_name', ''),
    COALESCE(
      (NEW.raw_user_meta_data->>'role')::public.user_role,
      'user'
    )
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

