-- ========================================================
-- WAMINNA HOTEL DATABASE SCHEMA
-- Target Database: Supabase PostgreSQL (waminna-staging)
-- ========================================================

-- 1. ENUMS & CUSTOM TYPES
CREATE TYPE public.room_type AS ENUM ('standard', 'deluxe', 'suite');
CREATE TYPE public.bed_type AS ENUM ('king', 'queen', 'twin');
CREATE TYPE public.room_status AS ENUM ('available', 'maintenance', 'occupied');
CREATE TYPE public.booking_status AS ENUM ('confirmed', 'pending', 'cancelled', 'completed');
CREATE TYPE public.payment_status AS ENUM ('paid', 'pending', 'refunded');
CREATE TYPE public.user_role AS ENUM ('guest', 'user', 'staff', 'owner');
CREATE TYPE public.addon_category AS ENUM ('dining', 'transport', 'wellness', 'convenience');

-- 2. PROFILES TABLE (Extends auth.users)
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    phone TEXT,
    role public.user_role NOT NULL DEFAULT 'user',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. ROOMS TABLE
CREATE TABLE public.rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    room_number TEXT NOT NULL UNIQUE,
    type public.room_type NOT NULL,
    capacity INT NOT NULL DEFAULT 2,
    bed_type public.bed_type NOT NULL,
    price_per_night NUMERIC(10, 2) NOT NULL,
    description TEXT NOT NULL,
    amenities TEXT[] DEFAULT '{}',
    photos TEXT[] DEFAULT '{}',
    status public.room_status NOT NULL DEFAULT 'available',
    size TEXT,
    view TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. ADDONS TABLE
CREATE TABLE public.addons (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    per_night BOOLEAN DEFAULT FALSE,
    category public.addon_category NOT NULL,
    icon TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. BOOKINGS TABLE
CREATE TABLE public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_reference TEXT UNIQUE NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    room_id BIGINT NOT NULL REFERENCES public.rooms(id) ON DELETE CASCADE,
    guest_first_name TEXT NOT NULL,
    guest_last_name TEXT NOT NULL,
    guest_email TEXT NOT NULL,
    guest_phone TEXT,
    special_requests TEXT,
    selected_addon_ids TEXT[] DEFAULT '{}',
    addon_total NUMERIC(10, 2) DEFAULT 0,
    check_in DATE NOT NULL,
    check_out DATE NOT NULL,
    guests_count INT NOT NULL DEFAULT 1,
    nights INT NOT NULL,
    subtotal NUMERIC(10, 2) NOT NULL,
    tax_amount NUMERIC(10, 2) NOT NULL,
    total_amount NUMERIC(10, 2) NOT NULL,
    status public.booking_status NOT NULL DEFAULT 'confirmed',
    payment_status public.payment_status NOT NULL DEFAULT 'paid',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. BLOCKED DATES TABLE
CREATE TABLE public.blocked_dates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES public.rooms(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    reason TEXT NOT NULL CHECK (reason IN ('booking', 'maintenance')),
    booking_id BIGINT REFERENCES public.bookings(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_room_date UNIQUE (room_id, date)
);

-- 7. REVIEWS TABLE
CREATE TABLE public.reviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    room_id BIGINT NOT NULL REFERENCES public.rooms(id) ON DELETE CASCADE,
    user_name TEXT NOT NULL,
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    comment TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ========================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ========================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.addons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blocked_dates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Rooms, Addons, Reviews, Blocked Dates: Public Read
CREATE POLICY "Public Read Rooms" ON public.rooms FOR SELECT USING (true);
CREATE POLICY "Public Read Addons" ON public.addons FOR SELECT USING (true);
CREATE POLICY "Public Read Reviews" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "Public Read Blocked Dates" ON public.blocked_dates FOR SELECT USING (true);

-- Bookings Policies: Anyone can create bookings, look up bookings by reference/email
CREATE POLICY "Public Insert Bookings" ON public.bookings FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Read Own Bookings" ON public.bookings FOR SELECT USING (true);

-- Profiles Policies
CREATE POLICY "Public Read Profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "User Update Own Profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
